name: .NET

on:
  push:
    branches: [ master ]

env:
  DOTNET_SDK_VERSION: '6.0.100-preview.4.21255.9'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: true
    - name: Build
      run: dotnet build

  publish-windows:
    runs-on: windows-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: true
    - name: Publish Windows x64 Release
      run: |
        dotnet publish -c Release -r win-x64 -o WindowsBuildx64
        del WindowsBuildx64\*.pdb
        del WindowsBuildx64\*.json
    - name: Upload Windows x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Windows_x64
        path: WindowsBuildx64

  publish-linux:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: true
    - name: Install Kerberos 5 library
      run: |
        sudo apt update
        sudo apt install -y libkrb5-dev
    - name: Publish Linux x64 Release
      run: |
        dotnet publish -c Release -r linux-x64 -o LinuxBuildx64
        rm LinuxBuildx64/*.pdb LinuxBuildx64/*.json
        strip LinuxBuildx64/SysuH3C
    - name: Upload Linux x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: Linux_x64
        path: LinuxBuildx64
        
  publish-macos:
    runs-on: macos-latest
    needs: build

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
        include-prerelease: true
    - name: Publish macOS x64 Release
      run: |
        dotnet publish -c Release -r osx-x64 -o macOSBuildx64
        rm macOSBuildx64/*.pdb macOSBuildx64/*.json
        strip macOSBuildx64/SysuH3C
    - name: Upload macOS x64 artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: macOS_x64
        path: macOSBuildx64
